name: travel_app_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  d_method: ^0.2.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
